#!/usr/bin/env python
# -*- coding=utf-8 -*-


"""
file: client.py
socket client
"""

import socket
import sys


def socket_client():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)#定义socket类型，网络通信，TCP
                                                             #socket.SOCK_STREAM，流式socket , for TCP
        s.connect(('127.0.0.1', 6666))  #要连接的IP与端口

    except socket.error as msg: #如果连接出错，
        print msg
        sys.exit(1) #退出程序
    print s.recv(1024)   #接收欢迎消息
    while 1:
        data = raw_input('please input work: ')
        s.send(data)  #将输入的字符发送给服务端
        print s.recv(1024) #把接收的数据定义为变量，并输出
        if data == 'exit':
            break
    s.close()


if __name__ == '__main__':
    socket_client()



